# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ONyg1SOWOsx6z2D3VPMrpo8irPMdP3wG
"""

import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier

data=pd.read_csv("https://raw.githubusercontent.com/SergioNoivak/KNN/master/iris.csv")
data

data.isnull().sum()

x=data[['sepal.length','sepal.width','petal.length','petal.width']]
y=data['variety']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)  #spliting of data in random manner

model=KNeighborsClassifier()
model.fit(x_train,y_train)

from sklearn import metrics
y_pred=model.predict(x_test)
acc=metrics.accuracy_score(y_test,y_pred)
print(acc)